### Create transfer
POST http://localhost:8080/transfers
Content-Type: application/json

{
  "source_wallet_id": "6a123a2d-57cb-42a4-8c4c-0947eccf28f0",
  "destination_wallet_id": "467656ed-bd83-44d1-aff5-1db653135b1f",
  "amount": 500,
  "currency": "BRL"
}

### Get transfer by id
GET http://localhost:8080/transfers/{{transfer_id}}

### Create transfer - wallet not found (404)
POST http://localhost:8080/transfers
Content-Type: application/json

{
  "source_wallet_id": "00000000-0000-0000-0000-000000000000",
  "destination_wallet_id": "00000000-0000-0000-0000-000000000000",
  "amount": 100,
  "currency": "BRL"
}

### Create transfer - insufficient balance (400)
POST http://localhost:8080/transfers
Content-Type: application/json

{
  "source_wallet_id": "{{source_wallet_id}}",
  "destination_wallet_id": "{{destination_wallet_id}}",
  "amount": 999999,
  "currency": "BRL"
}

### Create transfer - missing fields (400)
POST http://localhost:8080/transfers
Content-Type: application/json

{
  "source_wallet_id": "",
  "destination_wallet_id": "",
  "amount": 100
}
